# Generated by Django 3.2.5 on 2022-02-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsPai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_pai', models.CharField(max_length=400)),
                ('data', models.DateField(auto_now_add=True, verbose_name='data_pesquisa')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo da pagina')),
            ],
        ),
        migrations.CreateModel(
            name='UrlsFilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField(verbose_name='urls filho')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.urlspai')),
            ],
        ),
    ]
