# Generated by Django 3.2.5 on 2022-02-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_pai', models.CharField(max_length=400)),
                ('data', models.DateField(auto_now_add=True, verbose_name='data_pesquisa')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo da pagina')),
                ('pontos', models.IntegerField(verbose_name='pontos')),
            ],
        ),
        migrations.DeleteModel(
            name='UrlsFilho',
        ),
        migrations.DeleteModel(
            name='UrlsPai',
        ),
    ]
