# Generated by Django 3.2.5 on 2022-02-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20220206_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='links',
        ),
    ]
