# Generated by Django 3.2.5 on 2022-02-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_rename_urls_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='link_pai',
            new_name='link',
        ),
    ]
